### ISSUE TITLE
Support for React 18?

### ISSUE THREAD

**Issue by jasopolis** [gooddata/gooddata-ui-sdk#3201]
Are there any plans to support React 18 in @gooddata/sdk-ui*, even if just as a peer dependency?

**Comment by boriboris** [comment]
Hello Jas, 
Yes, there are plans to support react 18. It should be added sometimes next year (probably Q1 23 or Q2 23).

**Comment by boriboris** [comment]
Hello Jas,

Today we released v9 of our UI.SDK which supports the react 18.

**Comment by kandl** [comment]
Closing as GoodData.UI v9 supports React 18.
More details in https://www.gooddata.com/docs/gooddata-ui/latest/architecture/whats_new/
