### ISSUE TITLE
Hostname option for backend requires protocol

### ISSUE THREAD

**Issue by kaesve** [gooddata/gooddata-ui-sdk#3422]
We started using GoodData UI, and everything seemed to work except exporting. After some debugging, it turned out that the issue was caused by doing

```
const backend = bearFactory({
  hostname: "<ourtenant>.on.gooddata.com"
});
```

instead of

```
const backend = bearFactory({
  hostname: "https://<ourtenant>.on.gooddata.com"
});
```

This was easy to fix, but finding the cause was harder than necessary. Most things work when you do not add the protocol to the hostname. As far as I can tell, the direct cause of the error is:

```
new URL(resultUri, ctx.backend.config.hostname)
```

Which fails with `TypeError: URL constructor: <tenant>.on.gooddata.com is not a valid URL.`.

Ideally, the url would be checked immediately on creation of the backend instance.

**Comment by BugsBunny338** [comment]
Thanks for reporting this!

After internal investigation the hostname's base URL **must** have a protocol specified.

Not providing the protocol results in a failure described in the issue. Currently, we are not planning on addressing this unless prioritized. UX could definitely be improved, but for now we consider it as misconfiguration.

Hope this answer helps anyone who encounters the `TypeError: URL constructor: <tenant>.on.gooddata.com is not a valid URL.` error.
